#pragma kernel CalculateImage
#include "UnityCG.cginc"

//RWTexture2D<float4> CalculatedImage;
RWTexture2D<half4> Image;
Texture2D<half4> Image2D;
Texture2D<half4> ImageMask;


[numthreads(8,8,1)]
void CalculateImage(uint3 id : SV_DispatchThreadID)
{
    half4 ImageValues = Image[id.xy];
    half4 MaskValues = ImageMask[id.xy];
    half4 Image2DValues = Image2D[id.xy];
    Image[id.xy] = Image2DValues*MaskValues;
    
   
}
